config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
      get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      delete '/logout',  to: 'sessions#destroy'

  get 'users/new'

      root 'products#index'
      get  '/help',    to: 'static_pages#help'
      get  '/about',   to: 'static_pages#about'
      get  '/contact', to: 'static_pages#contact'
       get  '/signup',  to: 'users#new'
       get  '/admin',  to: 'admin#login'

       resources :users
       resources :charges
        resources :purchases,only: [:show]
         resources :products,only: [:index, :show]
    end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	def price_in_cents
		self.price*100
end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	after_create :email_purchaser
	def email_purchaser
		PurchaseMailer.purchase_receipt(self).deliver
	end	
end

app/models/user.rb
 class User < ApplicationRecord
 	 attr_accessor :remember_token
      validates :name, presence: true, length: { in: 9..30 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  
   validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
 # Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ?    
                    BCrypt::Engine::MIN_COST :
                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

  # Remembers a user in the database; enables persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, 
                    User.digest(remember_token))
      end


 # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
       # Forget a user session.
       def forget
          update_attribute(:remember_digest, nil)
       end
    end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def create
  # Amount in cents


  product=Product.find(params[:product_id])
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken],
    :plan => product.sku
  )

  
 

 purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], 
  amount: product.price_in_cents, description: product.description,
   currency: "usd", customer_id: customer.id, product_id: product.id)

redirect_to purchase
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
		
	end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products=Product.all
	end
	def show
   
    @product=Product.find(params[:id])
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase=Purchase.find(params[:id])
		@product=Product.find(@purchase.product_id)
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
      remember user 
        	redirect_to user
          # Log the user in and redirect to their profile page.
        else
          flash[:danger] = 'Invalid email/password combination'
          render 'new'
        end
     end

      
   


      

      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end

      def destroy
        log_out if logged_in?
        redirect_to root_url
      end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
<<<<<<< HEAD
  def contact
  end
  
=======
def contact
	
end
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
      def admin
      end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

      def show
        @user = User.find(params[:id])
        
      end

       def new
        @user = User.new
      end
     def create
        secure_params = params.require(:user).permit(:name, :email, 
                                  :password, :password_confirmation)
        @user = User.new(secure_params)
        if @user.save
         remember @user      
      flash[:success] = "Welcome to the Sample App!"    
          redirect_to @user
        else
            render 'new'
        end
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
 module SessionsHelper

      # Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end
       def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end
       # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end


 # Forget a persistent user session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end

      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end


    end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
 module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end

    end

app/views/layouts/_footer.html.erb
 <footer class="footer">
      
      <small>
        The main reference is <a href="https://dashboard.stripe.com/test/dashboard">stripe</a>
        
      </small>
      <nav>
        <ul>
<<<<<<< HEAD
          
=======
         
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="https://www.amazon.cn/">Other wwbsite</a></li>
        </ul>
      </nav>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "shopping website", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
             
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                 <li><%= link_to "Admin", admin_path %></li>
                 
                  
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
      <head>
        <title><%= yield(:title) %> | Shopping website</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                                  'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
      </head>
      <body>

        <header class="navbar navbar-fixed-top navbar-inverse">
          <div class="container">
            <%= link_to "shopping website", '#', id: "logo" %>
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",   '#' %></li>
                <li><%= link_to "Help",   '#' %></li>
                <li><%= link_to "Log in", '#' %></li>
              </ul>
            </nav>
          </div>
        </header>
         <%= render 'layouts/header' %>
        <div class="container">
          <% flash.each do |message_type, message| %>    <!-- START NEW CODE  -->
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>                                      <!-- END NEW CODE  -->
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
        </div>
      </body>
    </html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>your title</title>
  </head>

  <body>
    <%= yield %>
    <P>Thanks for you purchase</P>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products List</h1>

<section id="products">

	<%= @products.each do |product|%>
	<div  class="product prefix">
		<a href="<%= product_path(product)%>">
		<img  class="productimg" src="<%=asset_path product.image_name %>" alt="<%= product.title %>"/>
		
	</div>
<<<<<<< HEAD
    <p  style="font-size: 30px; text-align:center " class="product-title">price :$<%= product.price%></p>
=======
	<p  style="font-size: 30px; text-align:center " class="product-title">price :$<%= product.price%></p>
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
    <p  style="font-size: 30px; text-align:center " class="product-title">name :<%= product.title%></p>
    </a>
	
	<% end %>

</section>

app/views/products/show.html.erb
 <% provide(:title, 'You product') %>
    <h1>This is you receipt!</h1>
    <h2>Produce name is <%= @product.title%> </h2>
   
    <h2>Produce details :<%= @product.subtitle%></h2> 
    <h2><%= @product.description%></h2>

    
  <%= form_tag charges_path,id:'chargeForm' do %>

    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  

  <script src="https://checkout.stripe.com/checkout.js" ></script>
  <%=hidden_field_tag 'stripeToken'%>
  
  <%=hidden_field_tag 'amount',@product.price_in_cents%>

   <%=hidden_field_tag 'stripeEmail'%>
   <%=hidden_field_tag 'product_id',@product.id%>
   <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block">
    <span class="glyphicon glyphicon-ok">Buy this!</span>
   </button>

   <script>
    var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    token: function(token, arg) {
      document.getElementById("stripeToken").value = token.id;
      document.getElementById("stripeEmail").value = token.email;
      document.getElementById("chargeForm").submit();
    }
  });
  document.getElementById('btn-buy').addEventListener('click', function(e) {
  
  handler.open({
    name: "YOU PAYMENT",
    description: "<%= @product.title%>($<%= @product.price%>)",
    amount: document.getElementById("amount").value
  });
  e.preventDefault();
});
 </script>
 
        
<% end %>

app/views/purchases/show.html.erb
<h1>This is your purchase</h1>
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
<h3>Product title is :<%= @product.title%></h3>
<h3>Product subtitle is :<%= @product.subtitle%></h3>
<h3>Product price is :$<%= @product.price%></h3>
<h3><%= @product.description%></h3>

<<<<<<< HEAD
<h3>Here is <a href=https://s3-us-west-2.amazonaws.com/rails-shoppingapp-bucket/hotpot.jpg>you file</h3>
=======
<h3>Here is <a href=https://s3-us-west-2.amazonaws.com/rails-shoppingapp-bucket/bag.jpg>you file</h3>
=======
<p>Your purchase is <%= @purchase.inspect %></p>
<p>Here is <a href=https://s3-us-west-2.amazonaws.com/rails-shoppingapp-bucket/hotpot.jpg>you file</p>
>>>>>>> 4a859e6580592cd900e2035aa18e6193abb93ef2
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd

<img src='https://s3-us-west-2.amazonaws.com/rails-shoppingapp-bucket/thanks.jpg'/>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/static_pages/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title>Login | Myshopping</title>

    <link rel="stylesheet" media="screen" href="/assets/active_admin.self-88cbbe23aecfd489108fe7f15a29fb15e4449b4650847ca58c24aeba8e0407f2.css?body=1" />
    <link rel="stylesheet" media="print" href="/assets/active_admin/print.self-ec81b36f6786484af66638eee65f83f1ba8dead9a60a6bed19a921848d29a0f7.css?body=1" />
    <script src="/javascripts/active_admin.js"></script>

  

    <meta name="robots" content="noindex, nofollow" />

  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="ISkk9/QJXivg5Sf6BmvlTNAHgYDI+FPgXXRGzgCRoIFbB+IPdzhv+N0YiSwShJ/MQnL5lWo2Zb+s6EcavI8EPA==" />
</head>
<body class="active_admin logged_out new">
<div id="wrapper">

  <div id="content_wrapper">
      <div class="flash flash_alert">You need to sign in or sign up before continuing.</div>
    <div id="active_admin_content">
      <div id="login">
  <h2>Myshopping Login</h2>

  <form id="session_new" novalidate="novalidate" class="formtastic admin_user" action="/admin/login" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="Kr7n3Vk8IFra9v93aRD+Oz6iXse/3coFLWuqQHmrDV1QkCEl2g0RiecLUaF9/4S7rNcm0h0T/Frc96uUxbWp4A==" /><fieldset class="inputs"><ol><li class="email input required autofocus stringish" id="admin_user_email_input"><label for="admin_user_email" class="label">Email<abbr title="required">*</abbr></label><input id="admin_user_email" autofocus="autofocus" type="email" value="" name="admin_user[email]" />

</li><li class="password input required stringish" id="admin_user_password_input"><label for="admin_user_password" class="label">Password<abbr title="required">*</abbr></label><input maxlength="128" id="admin_user_password" type="password" name="admin_user[password]" />

</li><li class="boolean input optional" id="admin_user_remember_me_input"><input type="hidden" name="admin_user[remember_me]" value="0" /><label for="admin_user_remember_me" class=""><input type="checkbox" name="admin_user[remember_me]" id="admin_user_remember_me" value="1" />Remember me</label>

</li></ol></fieldset><fieldset class="actions"><ol><li class="action input_action " id="admin_user_submit_action"><input type="submit" name="commit" value="Login" data-disable-with="Login" /></li></ol></fieldset></form>

  

  <a href="/admin/password/new">Forgot your password?</a><br />




</div>

    </div>
  </div>
  <div id="footer">
    
  </div>
</div>
</body>
</html>

app/views/static_pages/contact.html.erb
<<<<<<< HEAD
=======

>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
 <!DOCTYPE html>
    <html>
      <head>
        <title>Contact | Shopping website</title>
      </head>
      <body>
        <h1>Contact</h1>
        <h3>
<<<<<<< HEAD
        Linkman is hope in this website,she eamil is www.420426962.com@qq.com
=======
        If you have problem in this website,please call hope,she eamil is www.420426962.com@qq.com
>>>>>>> a16b365c7a6a47ec436651520bc2017bd522c3cd
          
        </h3>
      </body>
    </html>

app/views/static_pages/help.html.erb
 <!DOCTYPE html>

    <html>
      <head>
        <title>Help | Shopping website</title>
      </head>
      <body>
        <h1>Help</h1>
        <h3>
        If you have problem in this website,please call hope,she eamil is www.420426962.com@qq.com
          
        </h3>
      </body>
    </html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
    <div class="center jumbotron">
      <h1>Welcome to the shopping website!</h1>

     

<section id="products">

  <%= @products.each do |product|%>
  <div class="product prefix">
    <a href="<%= product_path(product)%>">
    <img src="<%=asset_path product.image_name %>" alt="<%= product.title %>"/>
    <span class="product-price">$<%= product.price %></span>
  </div>
    <p class="product-title"><%= product.title%></p>
    </a>
  
  <% end %>

</section>

      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>   <!--  CHANGED LINE -->
    </div>      

    <%= link_to image_tag("rails.png", alt: "Rails logo"),
                'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
    <h1>Sign up</h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %> 
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

app/views/users/show.html.erb
 <% provide(:title, @user.name) %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
          </h1>
        </section>
      </aside>
    </div>